name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip
        pip install pytest
        pip install pandas
    - name: Test with pytest
      run: |
        pytest